# Generated by Django 4.2 on 2025-03-04 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0004_alter_product_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('tea', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='blog_post', to='shop.product')),
            ],
        ),
    ]
