# Generated by Django 4.2 on 2025-03-08 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_picture'),
        ('brewsreviews', '0002_blogpost_date_added_alter_blogpost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='tea',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blog_post', to='shop.product'),
        ),
    ]
