# Generated by Django 4.2 on 2025-06-19 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_userprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='subscribed_to_email',
            new_name='subscribed_to_members_club',
        ),
    ]
