# Generated by Django 4.2 on 2025-02-17 00:55

import checkout.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_orderitem_quantity_alter_orderitem_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_cost',
            field=models.IntegerField(default=3, validators=[checkout.models.validate_delivery_cost]),
        ),
    ]
