# Generated by Django 4.2 on 2025-02-20 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_order_delivery_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='lineitem_total',
            new_name='item_total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stripe_pid',
        ),
    ]
