# Generated by Django 4.2 on 2025-02-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_rename_lineitem_total_orderitem_item_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_taken',
            field=models.BooleanField(default=False),
        ),
    ]
