# Generated by Django 4.2 on 2025-03-01 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_order_payment_taken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_taken',
        ),
    ]
