# Generated by Django 4.2 on 2025-05-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_remove_order_payment_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_line1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='postcode',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='town_or_city',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
