# Generated by Django 4.2 on 2025-06-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_clear_order_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='weight',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
