from django import forms
from .models import Order


class OrderForm(forms.ModelForm):
    """
    Form to fill out order details
    Taken and adapted from Code Institute's boutique Ado walkthrough
    """

    delivery_cost = forms.DecimalField(
        max_digits=2,
        required=False,
        widget=forms.HiddenInput(),
    )

    grand_total = forms.DecimalField(
        max_digits=10,
        decimal_places=2,
        required=False,
        widget=forms.HiddenInput(),
    )

    class Meta:
        model = Order
        fields = (
            "full_name",
            "email",
            "phone_number",
            "address_line1",
            "address_line2",
            "town_or_city",
            "state_or_region",
            "country",
            "postcode",
            "delivery_cost",
            "grand_total",
        )

    def __init__(self, *args, **kwargs):
        """
        Add placeholders and classes, remove autogenerated
        labels and set autofocus on first field
        """
        super().__init__(*args, **kwargs)
        placeholders = {
            "full_name": "Full name",
            "email": "Email Address",
            "phone_number": "Phone Number",
            "address_line1": "Address Line 1",
            "address_line2": "Address Line 2",
            "town_or_city": "Town or City",
            "postcode": "Postcode",
            "state_or_region": "State or Region",
            "country": "Country",
        }

        self.fields["full_name"].widget.attrs["autofocus"] = True

        for field in self.fields:
            if field in ["delivery_cost", "grand_total"]:
                continue
            if field != "country":
                if self.fields[field].required:
                    placeholder = f"{placeholders[field]} *"
                else:
                    placeholder = placeholders[field]
                self.fields[field].widget.attrs["placeholder"] = placeholder

            self.fields[field].widget.attrs["class"] = "stripe-style-input"
            self.fields[field].label = False
