# Generated by Django 4.2 on 2025-02-09 20:58

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                        )),
                ('name', models.CharField(max_length=65)),
                ('sku', models.CharField(
                    default=shop.models.generate_sku,
                    max_length=8,
                    unique=True)),
                ('tea_type', models.IntegerField(
                    choices=[(0, 'Black'), (1, 'Green'), (2, 'Herbal')],
                    default=0)),
                ('base_price_number', models.DecimalField(
                    decimal_places=2,
                    max_digits=4
                    )),
                ('picture', models.ImageField(
                    blank=True,
                    default='camellia-sinensis.jpg',
                    null=True,
                    upload_to='products/'
                    )),
            ],
        ),
    ]
