# Generated by Django 4.2 on 2025-02-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20250209_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(
                blank=True,
                default='camellia-sinensis.jpg',
                upload_to='products/'
            ),
        ),
    ]
