# Generated by Django 4.2 on 2025-02-10 19:46

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(
                blank=True,
                default='camellia-sinensis.jpg',
                upload_to=shop.models.product_image_upload_path
            ),
        ),
    ]
