# Generated by Django 4.2 on 2025-03-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='caffeine_level',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Caffeine-Free', 'Caffeine-Free')], default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='flavor_profile',
            field=models.CharField(choices=[('Floral', 'Floral'), ('Fruity', 'Fruity'), ('Earthy', 'Earthy'), ('Malty', 'Malty'), ('Smoky', 'Smoky'), ('Others', 'Others')], default='Others', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.CharField(choices=[('China', 'China'), ('India', 'India'), ('Japan', 'Japan'), ('Sri Lanka', 'Sri Lanka'), ('Taiwan', 'Taiwan'), ('Others', 'Others')], default='Others', max_length=20),
        ),
    ]
