# Generated by Django 4.2 on 2025-03-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_caffeine_level_product_flavor_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='origin',
            field=models.CharField(choices=[('China', 'China'), ('India', 'India'), ('Japan', 'Japan'), ('Sri Lanka', 'Sri Lanka'), ('Kenya', 'Kenya'), ('Others', 'Others')], default='Others', max_length=20),
        ),
    ]
