# Generated by Django 4.2 on 2025-03-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_product_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='flavor_profile',
            field=models.CharField(choices=[('Floral', 'Floral'), ('Fruity', 'Fruity'), ('Earthy', 'Earthy'), ('Malty', 'Malty'), ('Others', 'Others')], default='Others', max_length=20),
        ),
    ]
