# Generated by Django 4.2 on 2025-03-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='subject',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
